# ШАБЛОН секрета
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "change_me"
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=habits;Username=postgres;Password=change_me"
